"/first":
  destination: "127.0.0.1:8081"
  middleware: []

"/second":
  destination: "127.0.0.1:8082"
  middleware: []

"/third":
  destination: "127.0.0.1:8083"
  middleware: []

"/fourth":
  destination: "127.0.0.1:8084"
  middleware: []
