"first.localhost:8080":
  destination: "127.0.0.1:8081"
  middleware: []

"second.localhost:8080":
  destination: "127.0.0.1:8082"
  middleware: []

"third.localhost:8080":
  destination: "127.0.0.1:8083"
  middleware: []
