server:
  address: :8080
  read_timeout: 10
  healthcheck_internal: 10

routes:
  /first:
    upstreams:
      - "http://localhost:8081"
      - "http://localhost:8082"
      - "http://localhost:8084"
    lb_policy: "round_robin" # "random", "round_robin"
    middleware:
      logger:
        stream: stdout
        mode: dev
      rate_limiter:
        rqs: 5

  /second:
    upstreams: ["http://127.0.0.1:8083", "http://127.0.0.1:8085"]
    middleware:
      logger:
        stream: stdout
        mode: prod
      rate_limiter:
        rqs: 1
