server:
  address: :8080
  read_timeout: 10

routes:
  /first:
    upstreams: ["http://localhost:8081"]
    middleware: []

  /second:
    upstreams: ["http://127.0.0.1:8082"]
    middleware: []

  /third:
    upstreams: ["http://127.0.0.1:8083"]
    middleware: []
