server:
  address: :8080
  read_timeout: 10
  healthcheck_internal: 10

routes:
  /first:
    upstreams:
      - "http://localhost:8081"
      - "http://localhost:8082"
      - "http://localhost:8084"
    lb_policy: "round_robin" # "random", "round_robin"
    middleware:
      # Order of these configurations is matters
      logger:
        stream: first-route.log
        mode: text
      rate_limiter:
        max_requests: 4
        time_frame_seconds: 30

  /second:
    upstreams: ["http://127.0.0.1:8083", "http://127.0.0.1:8085"]
    middleware:
      # Order of these configurations is matters
      # But should it matter?
      rate_limiter:
        max_requests: 2
        time_frame_seconds: 60  # Eventually support time as string, e.g. 2d
      basic_auth:
        file: ./examples/basic_auth
      cache_control:
        duration: 30s
      logger:
        stream: stdout
        mode: text
